### ISSUE TITLE
snow_records.py - Updated Status

### ISSUE THREAD

**Issue by DustinWi** [cloin/cloin.eda#4]
Are there plans to expand snow_records.py and get it certified for Hub?

Some SNOW administrators are hesitant or resource limited and are not as willing/able to install the EDA app in an instance of SNOW, and having a SNOW polling source would be very useful in our environment.  However, without the collection/source being in HUB I do not know if I can get it installed in our environment.

**Comment by cloin** [comment]
I personally haven't heard of any plans to certify this plugin or create a polling plugin for SNOW at this time.

**Comment by DustinWi** [comment]
Good enough response for me. LoL 
Thanks for getting back to me.
